name: Generate Snake

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/snake.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Akshat394
          svg_out_path: output/github-contribution-grid-snake-sissa.svg
          snake_color: '5ce1e6'
          snake_outline: true
          snake_animate: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 